"""Добавлены Attraction и Banner, обновлена Excursion

Revision ID: aa69589f6a8f
Revises: 0020ade80dcd
Create Date: 2025-07-21 16:16:33.639329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa69589f6a8f'
down_revision = '0020ade80dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('excursion_attraction',
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.id'], ),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursion.id'], ),
    sa.PrimaryKeyConstraint('excursion_id', 'attraction_id')
    )
    with op.batch_alter_table('excursion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excursion', schema=None) as batch_op:
        batch_op.drop_column('duration_hours')

    op.drop_table('excursion_attraction')
    op.drop_table('attraction')
    op.drop_table('banner')
    # ### end Alembic commands ###
